# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'poosub(0f8eace0-2836-455e-bdaa-aaceead97ced)'
    subscriptionId: '0f8eace0-2836-455e-bdaa-aaceead97ced'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'poorg'
    location: 'South India'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'poosub(0f8eace0-2836-455e-bdaa-aaceead97ced)'
    subscriptionId: '0f8eace0-2836-455e-bdaa-aaceead97ced'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'poorg'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'