# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'poosub(1)(0f8eace0-2836-455e-bdaa-aaceead97ced)'
    subscriptionId: '0f8eace0-2836-455e-bdaa-aaceead97ced'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'poorg'
    location: 'Central India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://dev.azure.com/vijay3016/_git/poo?path=%2Ftemplate.json&version=GBmain'
    csmParametersFileLink: 'https://dev.azure.com/vijay3016/_git/poo?path=%2Fparameters.json&version=GBmain'
    deploymentMode: 'Incremental'
  displayName: 'Run a one-line script'
